// Package main provides a code generator for Mixin patterns
// Mixin 代码生成器：将 Mixin 方法直接生成到目标类型中
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

// MixinDef 定义 Mixin 结构
type MixinDef struct {
	Name       string
	Target     string
	Methods    []MethodInfo
	ImportPath string
}

// MethodInfo 方法信息
type MethodInfo struct {
	Name     string
	Params   string
	Results  string
	Body     string
	Comments string
}

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: mixingen <config-file>")
		fmt.Println("Example: mixingen mixin.yaml")
		os.Exit(1)
	}

	configFile := os.Args[1]
	config, err := parseConfig(configFile)
	if err != nil {
		fmt.Printf("Error parsing config: %v\n", err)
		os.Exit(1)
	}

	if err := generateMixin(config); err != nil {
		fmt.Printf("Error generating mixin: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Mixin code generated successfully!")
}

func parseConfig(file string) (*MixinDef, error) {
	content, err := os.ReadFile(file)
	if err != nil {
		return nil, err
	}

	lines := strings.Split(string(content), "\n")
	def := &MixinDef{}

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "mixin:") {
			def.Name = strings.TrimSpace(strings.TrimPrefix(line, "mixin:"))
		} else if strings.HasPrefix(line, "target:") {
			def.Target = strings.TrimSpace(strings.TrimPrefix(line, "target:"))
		} else if strings.HasPrefix(line, "import:") {
			def.ImportPath = strings.TrimSpace(strings.TrimPrefix(line, "import:"))
		}
	}

	return def, nil
}

func generateMixin(def *MixinDef) error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, def.ImportPath, nil, parser.ParseComments)
	if err != nil {
		return err
	}

	var methods []MethodInfo

	ast.Inspect(f, func(n ast.Node) bool {
		if fn, ok := n.(*ast.FuncDecl); ok {
			if fn.Recv != nil && len(fn.Recv.List) > 0 {
				if starExpr, ok := fn.Recv.List[0].Type.(*ast.StarExpr); ok {
					if ident, ok := starExpr.X.(*ast.Ident); ok {
						if ident.Name == def.Name {
							method := extractMethodInfo(fset, fn)
							methods = append(methods, method)
						}
					}
				}
			}
		}
		return true
	})

	def.Methods = methods
	return generateCode(def)
}

func extractMethodInfo(fset *token.FileSet, fn *ast.FuncDecl) MethodInfo {
	var params, results strings.Builder

	if fn.Type.Params != nil {
		for i, param := range fn.Type.Params.List {
			if i > 0 {
				params.WriteString(", ")
			}
			for j, name := range param.Names {
				if j > 0 {
					params.WriteString(", ")
				}
				params.WriteString(name.Name)
			}
			params.WriteString(" ")
			params.WriteString(exprToString(param.Type))
		}
	}

	if fn.Type.Results != nil {
		for i, res := range fn.Type.Results.List {
			if i > 0 {
				results.WriteString(", ")
			}
			results.WriteString(exprToString(res.Type))
		}
	}

	return MethodInfo{
		Name:    fn.Name.Name,
		Params:  params.String(),
		Results: results.String(),
	}
}

func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return exprToString(e.X) + "." + e.Sel.Name
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	case *ast.ArrayType:
		return "[]" + exprToString(e.Elt)
	case *ast.MapType:
		return "map[" + exprToString(e.Key) + "]" + exprToString(e.Value)
	case *ast.InterfaceType:
		return "interface{}"
	case *ast.FuncType:
		return "func()"
	case *ast.Ellipsis:
		return "..." + exprToString(e.Elt)
	default:
		return "interface{}"
	}
}

func generateCode(def *MixinDef) error {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by mixingen. DO NOT EDIT.\n")
	buf.WriteString("// Run \"go generate\" to update this file.\n\n")
	buf.WriteString("package core\n\n")

	buf.WriteString("import (\n")
	buf.WriteString("\t\"reflect\"\n")
	buf.WriteString("\t\"net/http\"\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\n")
	buf.WriteString("\t\"github.com/linuxerlv/gonest/core/abstract\"\n")
	buf.WriteString(")\n\n")

	for _, method := range def.Methods {
		if strings.HasPrefix(method.Name, "Use") {
			buf.WriteString(fmt.Sprintf("// %s is generated from MiddlewareMixin\n", method.Name))
			buf.WriteString(fmt.Sprintf("func (a *WebApplication) %s(%s) %s {\n",
				method.Name, method.Params, method.Results))
			buf.WriteString(generateMethodBody(method))
			buf.WriteString("}\n\n")
		}
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	return os.WriteFile("core/mixin_generated.go", formatted, 0644)
}

func generateMethodBody(method MethodInfo) string {
	middlewareName := strings.TrimPrefix(method.Name, "Use")
	middlewareKey := strings.ToLower(middlewareName)

	return fmt.Sprintf(`	cfg := a.services.GetService(reflect.TypeOf("%s"))
	if mw := create%sMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a
`, middlewareKey, middlewareName)
}
