// Code generated by mixingen. DO NOT EDIT.
// Run "go generate" to update this file.
//
// This file contains Mixin methods generated from MiddlewareMixin into WebApplication

package core

import (
	"reflect"
)

// UseCORS enables CORS middleware
func (a *WebApplication) UseCORS() *WebApplication {
	cfg := a.services.GetService(reflect.TypeOf("cors"))
	if mw := createCORSMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a
}

// UseRecovery enables recovery middleware
func (a *WebApplication) UseRecovery() *WebApplication {
	cfg := a.services.GetService(reflect.TypeOf("recovery"))
	if mw := createRecoveryMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a
}

// UseLogging enables logging middleware
func (a *WebApplication) UseLogging() *WebApplication {
	cfg := a.services.GetService(reflect.TypeOf("logging"))
	if mw := createLoggingMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a
}

// UseRateLimit enables rate limit middleware
func (a *WebApplication) UseRateLimit() *WebApplication {
	cfg := a.services.GetService(reflect.TypeOf("ratelimit"))
	if mw := createRateLimitMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a
}

// UseGzip enables gzip compression middleware
func (a *WebApplication) UseGzip() *WebApplication {
	cfg := a.services.GetService(reflect.TypeOf("gzip"))
	if mw := createGzipMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a
}

// UseSecurity enables security headers middleware
func (a *WebApplication) UseSecurity() *WebApplication {
	cfg := a.services.GetService(reflect.TypeOf("security"))
	if mw := createSecurityMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a
}

// UseRequestID enables request ID middleware
func (a *WebApplication) UseRequestID() *WebApplication {
	cfg := a.services.GetService(reflect.TypeOf("requestid"))
	if mw := createRequestIDMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a
}

// UseTimeout enables timeout middleware
func (a *WebApplication) UseTimeout() *WebApplication {
	cfg := a.services.GetService(reflect.TypeOf("timeout"))
	if mw := createTimeoutMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a
}
