// Package mixingen provides code generation for Mixin patterns
// 将 Mixin 方法直接生成到目标类型中
package mixingen

import (
	"bytes"
	"go/format"
	"io"
	"os"
	"reflect"
	"runtime"
	"strings"
	"text/template"
)

// Generator Mixin 代码生成器
type Generator struct {
	Package   string
	Target    string
	Mixin     string
	Methods   []MethodDef
	Imports   []string
	ExtraCode string
}

// MethodDef 方法定义
type MethodDef struct {
	Name        string
	Params      string
	Results     string
	Body        string
	Comment     string
	IsGenerated bool
}

// Config 生成器配置
type Config struct {
	Package   string
	Target    string
	Mixin     string
	Methods   []MethodDef
	Imports   []string
	ExtraCode string
}

// NewGenerator 创建生成器
func NewGenerator(config Config) *Generator {
	return &Generator{
		Package:   config.Package,
		Target:    config.Target,
		Mixin:     config.Mixin,
		Methods:   config.Methods,
		Imports:   config.Imports,
		ExtraCode: config.ExtraCode,
	}
}

// Generate 生成代码
func (g *Generator) Generate() ([]byte, error) {
	var buf bytes.Buffer

	if err := headerTemplate.Execute(&buf, g); err != nil {
		return nil, err
	}

	if err := importsTemplate.Execute(&buf, g); err != nil {
		return nil, err
	}

	if err := methodsTemplate.Execute(&buf, g); err != nil {
		return nil, err
	}

	if g.ExtraCode != "" {
		buf.WriteString("\n")
		buf.WriteString(g.ExtraCode)
	}

	return format.Source(buf.Bytes())
}

// WriteTo 写入文件
func (g *Generator) WriteTo(w io.Writer) (int64, error) {
	code, err := g.Generate()
	if err != nil {
		return 0, err
	}
	n, err := w.Write(code)
	return int64(n), err
}

// WriteFile 写入文件
func (g *Generator) WriteFile(filename string) error {
	code, err := g.Generate()
	if err != nil {
		return err
	}
	return os.WriteFile(filename, code, 0644)
}

var headerTemplate = template.Must(template.New("header").Parse(`// Code generated by mixingen. DO NOT EDIT.
// Run "go generate" to update this file.
// 
// This file contains Mixin methods generated from {{.Mixin}} into {{.Target}}

package {{.Package}}
`))

var importsTemplate = template.Must(template.New("imports").Parse(`
import (
{{- range .Imports}}
	{{.}}
{{- end}}
)
`))

var methodsTemplate = template.Must(template.New("methods").Parse(`
{{- range .Methods}}
{{if .Comment}}
// {{.Comment}}
{{- end}}
func (a *{{$.Target}}) {{.Name}}({{.Params}}) {{.Results}} {
{{.Body}}
}
{{- end}}
`))

// MiddlewareMixinMethods 中间件 Mixin 方法定义
var MiddlewareMixinMethods = []MethodDef{
	{
		Name:    "UseCORS",
		Params:  "",
		Results: "*WebApplication",
		Comment: "UseCORS enables CORS middleware",
		Body: `	cfg := a.services.GetService(reflect.TypeOf("cors"))
	if mw := createCORSMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a`,
	},
	{
		Name:    "UseRecovery",
		Params:  "",
		Results: "*WebApplication",
		Comment: "UseRecovery enables recovery middleware",
		Body: `	cfg := a.services.GetService(reflect.TypeOf("recovery"))
	if mw := createRecoveryMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a`,
	},
	{
		Name:    "UseLogging",
		Params:  "",
		Results: "*WebApplication",
		Comment: "UseLogging enables logging middleware",
		Body: `	cfg := a.services.GetService(reflect.TypeOf("logging"))
	if mw := createLoggingMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a`,
	},
	{
		Name:    "UseRateLimit",
		Params:  "",
		Results: "*WebApplication",
		Comment: "UseRateLimit enables rate limit middleware",
		Body: `	cfg := a.services.GetService(reflect.TypeOf("ratelimit"))
	if mw := createRateLimitMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a`,
	},
	{
		Name:    "UseGzip",
		Params:  "",
		Results: "*WebApplication",
		Comment: "UseGzip enables gzip compression middleware",
		Body: `	cfg := a.services.GetService(reflect.TypeOf("gzip"))
	if mw := createGzipMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a`,
	},
	{
		Name:    "UseSecurity",
		Params:  "",
		Results: "*WebApplication",
		Comment: "UseSecurity enables security headers middleware",
		Body: `	cfg := a.services.GetService(reflect.TypeOf("security"))
	if mw := createSecurityMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a`,
	},
	{
		Name:    "UseRequestID",
		Params:  "",
		Results: "*WebApplication",
		Comment: "UseRequestID enables request ID middleware",
		Body: `	cfg := a.services.GetService(reflect.TypeOf("requestid"))
	if mw := createRequestIDMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a`,
	},
	{
		Name:    "UseTimeout",
		Params:  "",
		Results: "*WebApplication",
		Comment: "UseTimeout enables timeout middleware",
		Body: `	cfg := a.services.GetService(reflect.TypeOf("timeout"))
	if mw := createTimeoutMiddleware(cfg); mw != nil {
		a.middlewares = append(a.middlewares, mw)
	}
	return a`,
	},
}

// GenerateMiddlewareMixin 生成中间件 Mixin 代码
func GenerateMiddlewareMixin() ([]byte, error) {
	gen := NewGenerator(Config{
		Package: "core",
		Target:  "WebApplication",
		Mixin:   "MiddlewareMixin",
		Methods: MiddlewareMixinMethods,
		Imports: []string{
			`"reflect"`,
		},
	})
	return gen.Generate()
}

// ParseMethodFromFunc 从函数解析方法定义
func ParseMethodFromFunc(fn interface{}) MethodDef {
	t := reflect.TypeOf(fn)
	if t.Kind() != reflect.Func {
		return MethodDef{}
	}

	name := strings.TrimPrefix(runtime.FuncForPC(reflect.ValueOf(fn).Pointer()).Name(), "github.com/linuxerlv/gonest/core.")
	name = strings.Split(name, ".")[0]

	var params, results strings.Builder

	for i := 0; i < t.NumIn(); i++ {
		if i > 0 {
			params.WriteString(", ")
		}
		params.WriteString(t.In(i).String())
	}

	for i := 0; i < t.NumOut(); i++ {
		if i > 0 {
			results.WriteString(", ")
		}
		results.WriteString(t.Out(i).String())
	}

	return MethodDef{
		Name:    name,
		Params:  params.String(),
		Results: results.String(),
	}
}
